swagger: '2.0'
schemes:
  - https
host: management.azure.com
info:
  description: 'The Microsoft Azure ExpressRouteCrossConnection Resource Provider REST APIs describes the operations for the connectivity provider to provision ExpressRoute circuit, create and modify BGP peering entities and troubleshoot connectivity on customer''s ExpressRoute circuit. '
  title: ExpressRouteCrossConnection REST APIs
  version: '2018-12-01'
  x-apisguru-categories:
    - cloud
  x-logo:
    url: 'https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2018-12-01/expressRouteCrossConnection.json'
      version: '2.0'
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: network-expressRouteCrossConnection
  x-tags:
    - Azure
    - Microsoft
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  azure_auth:
    authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/authorize'
    description: Azure Active Directory OAuth2 Flow
    flow: implicit
    scopes:
      user_impersonation: impersonate your user account
    type: oauth2
security:
  - azure_auth:
      - user_impersonation
paths:
  '/subscriptions/{subscriptionId}/providers/Microsoft.Network/expressRouteCrossConnections':
    get:
      description: Retrieves all the ExpressRouteCrossConnections in a subscription.
      operationId: ExpressRouteCrossConnections_List
      parameters:
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful. The operation returns a list of ExpressRouteCrossConnection resources. If there are no cross connection resources an empty list is returned.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionListResult'
      tags:
        - ExpressRouteCrossConnections
      x-ms-examples:
        ExpressRouteCrossConnectionList:
          parameters:
            api-version: '2018-12-01'
            subscriptionId: subid
          responses:
            '200':
              body:
                value:
                  - id: /subscriptions/subid/resourceGroups/CrossConnectionSiliconValley/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>
                    location: brazilsouth
                    name: <circuitServiceKey>
                    properties:
                      bandwidthInMbps: 1000
                      expressRouteCircuit:
                        id: /subscriptions/subid/resourceGroups/ertest/providers/Microsoft.Network/expressRouteCircuits/er1
                      peeringLocation: SiliconValley
                      peerings: []
                      primaryAzurePort: bvtazureixp01
                      provisioningState: Enabled
                      sTag: 2
                      secondaryAzurePort: bvtazureixp01
                      serviceProviderProvisioningState: NotProvisioned
                    type: Microsoft.Network/expressRouteCrossConnections
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCrossConnections':
    get:
      description: Retrieves all the ExpressRouteCrossConnections in a resource group.
      operationId: ExpressRouteCrossConnections_ListByResourceGroup
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful.The operation returns a list of ExpressRouteCrossConnection resources. If there are no cross connection resources an empty list is returned.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionListResult'
      tags:
        - ExpressRouteCrossConnections
      x-ms-examples:
        ExpressRouteCrossConnectionListByResourceGroup:
          parameters:
            api-version: '2018-12-01'
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                value:
                  - id: /subscriptions/subid/resourceGroups/CrossConnectionSilicon-Valley/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>
                    location: brazilsouth
                    name: <circuitServiceKey>
                    properties:
                      bandwidthInMbps: 1000
                      expressRouteCircuit:
                        id: /subscriptions/subid/resourceGroups/ertest/providers/Microsoft.Network/expressRouteCircuits/er1
                      peeringLocation: SiliconValley
                      peerings: []
                      primaryAzurePort: bvtazureixp01
                      provisioningState: Enabled
                      sTag: 2
                      secondaryAzurePort: bvtazureixp01
                      serviceProviderProvisioningState: NotProvisioned
                    type: Microsoft.Network/expressRouteCrossConnections
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCrossConnections/{crossConnectionName}':
    get:
      description: Gets details about the specified ExpressRouteCrossConnection.
      operationId: ExpressRouteCrossConnections_Get
      parameters:
        - description: The name of the resource group (peering location of the circuit).
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection (service key of the circuit).
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful. The operation returns the resulting ExpressRouteCrossConnection resource.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnection'
      tags:
        - ExpressRouteCrossConnections
      x-ms-examples:
        GetExpressRouteCrossConnection:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                etag: W/"c0e6477e-8150-4d4f-9bf6-bb10e6acb63a"
                id: /subscriptions/subid/resourceGroups/CrossConnection-SiliconValley/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>
                location: brazilsouth
                name: <circuitServiceKey>
                properties:
                  bandwidthInMbps: 1000
                  expressRouteCircuit:
                    id: /subscriptions/subid/resourceGroups/ertest/providers/Microsoft.Network/expressRouteCircuits/er1
                  peeringLocation: SiliconValley
                  peerings: []
                  primaryAzurePort: bvtazureixp01
                  provisioningState: Enabled
                  sTag: 2
                  secondaryAzurePort: bvtazureixp01
                  serviceProviderProvisioningState: NotProvisioned
                type: Microsoft.Network/expressRouteCrossConnections
    patch:
      description: Updates an express route cross connection tags.
      operationId: ExpressRouteCrossConnections_UpdateTags
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the cross connection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: Parameters supplied to update express route cross connection tags.
          in: body
          name: crossConnectionParameters
          required: true
          schema:
            description: Tags object for patch operations.
            properties:
              tags:
                additionalProperties:
                  type: string
                description: Resource tags.
                type: object
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Update successful. The operation returns the resulting ExpressRouteCrossConnection resource.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnection'
      tags:
        - ExpressRouteCrossConnections
      x-ms-examples:
        UpdateExpressRouteCrossConnectionTags:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            crossConnectionParameters:
              tags:
                tag1: value1
                tag2: value2
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                id: /subscriptions/subid/resourceGroups/CrossConnectionSiliconValley/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>
                location: brazilsouth
                name: er1
                properties:
                  bandwidthInMbps: 1000
                  expressRouteCircuit:
                    id: /subscriptions/subid/resourceGroups/ertest/providers/Microsoft.Network/expressRouteCircuits/er1
                  peeringLocation: SiliconValley
                  peerings: []
                  primaryAzurePort: bvtazureixp01
                  provisioningState: Failed
                  sTag: 2
                  secondaryAzurePort: bvtazureixp01
                  serviceProviderProvisioningState: NotProvisioned
                tags:
                  tag1: value1
                  tag2: value2
                type: Microsoft.Network/expressRouteCrossConnections
      x-ms-long-running-operation: true
    put:
      description: Update the specified ExpressRouteCrossConnection.
      operationId: ExpressRouteCrossConnections_CreateOrUpdate
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: Parameters supplied to the update express route crossConnection operation.
          in: body
          name: parameters
          required: true
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnection'
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Update successful. The operation returns the resulting ExpressRouteCrossConnection resource.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnection'
      tags:
        - ExpressRouteCrossConnections
      x-ms-examples:
        UpdateExpressRouteCrossConnection:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            parameters:
              properties:
                serviceProviderProvisioningState: NotProvisioned
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                id: /subscriptions/subid/resourceGroups/CrossConnectionSiliconValley/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>
                location: brazilsouth
                name: <circuitServiceKey>
                properties:
                  bandwidthInMbps: 1000
                  expressRouteCircuit:
                    id: /subscriptions/subid/resourceGroups/ertest/providers/Microsoft.Network/expressRouteCircuits/er1
                  peeringLocation: SiliconValley
                  peerings: []
                  primaryAzurePort: bvtazureixp01
                  provisioningState: Enabled
                  sTag: 2
                  secondaryAzurePort: bvtazureixp01
                  serviceProviderProvisioningState: NotProvisioned
                type: Microsoft.Network/expressRouteCrossConnections
      x-ms-long-running-operation: true
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCrossConnections/{crossConnectionName}/peerings':
    get:
      description: Gets all peerings in a specified ExpressRouteCrossConnection.
      operationId: ExpressRouteCrossConnectionPeerings_List
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful. The operation returns a list of ExpressRouteCrossConnectionPeering resources.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionPeeringList'
      tags:
        - ExpressRouteCrossConnectionPeerings
      x-ms-examples:
        ExpressRouteCrossConnectionBgpPeeringList:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                value:
                  - etag: W/"72090554-7e3b-43f2-80ad-99a9020dcb11"
                    id: /subscriptions/subid/resourceGroups/CrossConnection-SiliconValley/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>/peerings/AzurePrivatePeering
                    name: AzurePrivatePeering
                    properties:
                      azureASN: 12076
                      gatewayManagerEtag: ''
                      ipv6PeeringConfig:
                        primaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::/126'
                        secondaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::4/126'
                        state: Enabled
                      lastModifiedBy: Customer
                      peerASN: 200
                      peeringType: AzurePrivatePeering
                      primaryAzurePort: ''
                      primaryPeerAddressPrefix: 192.168.16.252/30
                      provisioningState: Succeeded
                      secondaryAzurePort: ''
                      secondaryPeerAddressPrefix: 192.168.18.252/30
                      state: Enabled
                      vlanId: 200
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCrossConnections/{crossConnectionName}/peerings/{peeringName}':
    delete:
      description: Deletes the specified peering from the ExpressRouteCrossConnection.
      operationId: ExpressRouteCrossConnectionPeerings_Delete
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: The name of the peering.
          in: path
          name: peeringName
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Delete successful.
        '202':
          description: Accepted and the operation will complete asynchronously.
        '204':
          description: Delete successful.
      tags:
        - ExpressRouteCrossConnectionPeerings
      x-ms-examples:
        DeleteExpressRouteCrossConnectionBgpPeering:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            peeringName: AzurePrivatePeering
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200': {}
            '202': {}
            '204': {}
      x-ms-long-running-operation: true
    get:
      description: Gets the specified peering for the ExpressRouteCrossConnection.
      operationId: ExpressRouteCrossConnectionPeerings_Get
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: The name of the peering.
          in: path
          name: peeringName
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful. The operation returns the resulting ExpressRouteCrossConnectionPeering resource.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionPeering'
      tags:
        - ExpressRouteCrossConnectionPeerings
      x-ms-examples:
        GetExpressRouteCrossConnectionBgpPeering:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            peeringName: AzurePrivatePeering
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                etag: W/"72090554-7e3b-43f2-80ad-99a9020dcb11"
                id: /subscriptions/subid/resourceGroups/CrossConnection-Boydton1DC/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>/peerings/AzurePrivatePeering
                name: AzurePrivatePeering
                properties:
                  azureASN: 12076
                  gatewayManagerEtag: ''
                  ipv6PeeringConfig:
                    primaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::/126'
                    secondaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::4/126'
                    state: Enabled
                  lastModifiedBy: Customer
                  peerASN: 200
                  peeringType: AzurePrivatePeering
                  primaryAzurePort: ''
                  primaryPeerAddressPrefix: 192.168.16.252/30
                  provisioningState: Succeeded
                  secondaryAzurePort: ''
                  secondaryPeerAddressPrefix: 192.168.18.252/30
                  state: Enabled
                  vlanId: 200
    put:
      description: Creates or updates a peering in the specified ExpressRouteCrossConnection.
      operationId: ExpressRouteCrossConnectionPeerings_CreateOrUpdate
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: The name of the peering.
          in: path
          name: peeringName
          required: true
          type: string
        - description: Parameters supplied to the create or update ExpressRouteCrossConnection peering operation.
          in: body
          name: peeringParameters
          required: true
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionPeering'
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Update successful. The operation returns the resulting ExpressRouteCrossConnectionPeering resource.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionPeering'
        '201':
          description: Create successful. The operation returns the resulting ExpressRouteCrossConnectionPeering resource.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionPeering'
      tags:
        - ExpressRouteCrossConnectionPeerings
      x-ms-examples:
        ExpressRouteCrossConnectionBgpPeeringCreate:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            peeringName: AzurePrivatePeering
            peeringParameters:
              properties:
                ipv6PeeringConfig:
                  primaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::/126'
                  secondaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::4/126'
                peerASN: 200
                primaryPeerAddressPrefix: 192.168.16.252/30
                secondaryPeerAddressPrefix: 192.168.18.252/30
                vlanId: 200
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                etag: W/"72090554-7e3b-43f2-80ad-99a9020dcb11"
                id: /subscriptions/subid/resourceGroups/CrossConnection-Boydton1DC/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>/peerings/AzurePrivatePeering
                name: AzurePrivatePeering
                properties:
                  azureASN: 12076
                  gatewayManagerEtag: ''
                  ipv6PeeringConfig:
                    primaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::/126'
                    secondaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::4/126'
                    state: Enabled
                  lastModifiedBy: Customer
                  peerASN: 200
                  peeringType: AzurePrivatePeering
                  primaryAzurePort: ''
                  primaryPeerAddressPrefix: 192.168.16.252/30
                  provisioningState: Succeeded
                  secondaryAzurePort: ''
                  secondaryPeerAddressPrefix: 192.168.18.252/30
                  state: Enabled
                  vlanId: 200
            '201':
              body:
                etag: W/"72090554-7e3b-43f2-80ad-99a9020dcb11"
                id: /subscriptions/subid/resourceGroups/CrossConnection-SiliconValley/providers/Microsoft.Network/expressRouteCrossConnections/<circuitServiceKey>/peerings/AzurePrivatePeering
                name: AzurePrivatePeering
                properties:
                  azureASN: 12076
                  gatewayManagerEtag: ''
                  ipv6PeeringConfig:
                    primaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::/126'
                    secondaryPeerAddressPrefix: '3FFE:FFFF:0:CD30::4/126'
                    state: Enabled
                  lastModifiedBy: Customer
                  peerASN: 200
                  peeringType: AzurePrivatePeering
                  primaryAzurePort: ''
                  primaryPeerAddressPrefix: 192.168.16.252/30
                  provisioningState: Succeeded
                  secondaryAzurePort: ''
                  secondaryPeerAddressPrefix: 192.168.18.252/30
                  state: Enabled
                  vlanId: 200
      x-ms-long-running-operation: true
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCrossConnections/{crossConnectionName}/peerings/{peeringName}/arpTables/{devicePath}':
    post:
      description: Gets the currently advertised ARP table associated with the express route cross connection in a resource group.
      operationId: ExpressRouteCrossConnections_ListArpTable
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: The name of the peering.
          in: path
          name: peeringName
          required: true
          type: string
        - description: The path of the device
          in: path
          name: devicePath
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful. The operation returns the resulting ExpressRouteCrossConnectionsArpTable resource.
          schema:
            description: Response for ListArpTable associated with the Express Route Circuits API.
            properties:
              nextLink:
                description: The URL to get the next set of results.
                type: string
              value:
                description: Gets list of the ARP table.
                items:
                  description: The ARP table associated with the ExpressRouteCircuit.
                  properties:
                    age:
                      description: Entry age in minutes
                      format: int32
                      type: integer
                    interface:
                      description: Interface address
                      type: string
                    ipAddress:
                      description: The IP address.
                      type: string
                    macAddress:
                      description: The MAC address.
                      type: string
                type: array
        '202':
          description: Accepted and the operation will complete asynchronously.
      tags:
        - ExpressRouteCrossConnectionArpTable
      x-ms-examples:
        GetExpressRouteCrossConnectionsArpTable:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            devicePath: primary
            peeringName: AzurePrivatePeering
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                value:
                  - age: 0
                    interface: Microsoft
                    ipAddress: 192.116.14.254
                    macAddress: 885a.9269.9110
            '202': {}
      x-ms-long-running-operation: true
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCrossConnections/{crossConnectionName}/peerings/{peeringName}/routeTables/{devicePath}':
    post:
      description: Gets the currently advertised routes table associated with the express route cross connection in a resource group.
      operationId: ExpressRouteCrossConnections_ListRoutesTable
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: The name of the peering.
          in: path
          name: peeringName
          required: true
          type: string
        - description: The path of the device.
          in: path
          name: devicePath
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful. The operation returns the resulting ExpressRouteCrossConnectionsRouteTable resource.
          schema:
            description: Response for ListRoutesTable associated with the Express Route Circuits API.
            properties:
              nextLink:
                description: The URL to get the next set of results.
                type: string
              value:
                description: The list of routes table.
                items:
                  description: The routes table associated with the ExpressRouteCircuit
                  properties:
                    locPrf:
                      description: Local preference value as set with the set local-preference route-map configuration command
                      type: string
                    network:
                      description: IP address of a network entity
                      type: string
                    nextHop:
                      description: NextHop address
                      type: string
                    path:
                      description: Autonomous system paths to the destination network.
                      type: string
                    weight:
                      description: Route Weight.
                      format: int32
                      type: integer
                type: array
        '202':
          description: Accepted and the operation will complete asynchronously.
      tags:
        - ExpressRouteCrossConnectionRouteTable
      x-ms-examples:
        GetExpressRouteCrossConnectionsRouteTable:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            devicePath: primary
            peeringName: AzurePrivatePeering
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                value:
                  - locPrf: ''
                    network: 10.6.0.0/16
                    nextHop: 10.6.1.12
                    path: '65514'
                    weight: 0
                  - locPrf: ''
                    network: 10.7.0.0/16
                    nextHop: 10.7.1.13
                    path: '65514'
                    weight: 0
            '202': {}
      x-ms-long-running-operation: true
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCrossConnections/{crossConnectionName}/peerings/{peeringName}/routeTablesSummary/{devicePath}':
    post:
      description: Gets the route table summary associated with the express route cross connection in a resource group.
      operationId: ExpressRouteCrossConnections_ListRoutesTableSummary
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          type: string
        - description: The name of the ExpressRouteCrossConnection.
          in: path
          name: crossConnectionName
          required: true
          type: string
        - description: The name of the peering.
          in: path
          name: peeringName
          required: true
          type: string
        - description: The path of the device.
          in: path
          name: devicePath
          required: true
          type: string
        - description: Client API version.
          in: query
          name: api-version
          required: true
          type: string
        - description: The subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
          in: path
          name: subscriptionId
          required: true
          type: string
      responses:
        '200':
          description: Request successful. The operation returns the resulting ExpressRouteCrossConnectionsRouteTableSummary resource.
          schema:
            $ref: '#/definitions/ExpressRouteCrossConnectionsRoutesTableSummaryListResult'
        '202':
          description: Accepted and the operation will complete asynchronously.
      tags:
        - ExpressRouteCrossConnectionRouteTableSummary
      x-ms-examples:
        GetExpressRouteCrossConnectionsRouteTableSummary:
          parameters:
            api-version: '2018-12-01'
            crossConnectionName: <circuitServiceKey>
            devicePath: primary
            peeringName: AzurePrivatePeering
            resourceGroupName: CrossConnection-SiliconValley
            subscriptionId: subid
          responses:
            '200':
              body:
                value:
                  - asn: 65514
                    neighbor: 10.6.1.112
                    stateOrPrefixesReceived: Active
                    upDown: 1d14h
                  - asn: 65514
                    neighbor: 10.6.1.113
                    stateOrPrefixesReceived: '1'
                    upDown: 1d14h
            '202': {}
      x-ms-long-running-operation: true
definitions:
  ExpressRouteCircuitReference:
    properties:
      id:
        description: Corresponding Express Route Circuit Id.
        type: string
  ExpressRouteCrossConnection:
    allOf:
      - description: Common resource representation.
        properties:
          id:
            description: Resource ID.
            type: string
          location:
            description: Resource location.
            type: string
          name:
            description: Resource name.
            readOnly: true
            type: string
          tags:
            additionalProperties:
              type: string
            description: Resource tags.
            type: object
          type:
            description: Resource type.
            readOnly: true
            type: string
        x-ms-azure-resource: true
    description: ExpressRouteCrossConnection resource
    properties:
      etag:
        description: Gets a unique read-only string that changes whenever the resource is updated.
        readOnly: true
        type: string
      properties:
        $ref: '#/definitions/ExpressRouteCrossConnectionProperties'
        x-ms-client-flatten: true
  ExpressRouteCrossConnectionListResult:
    description: Response for ListExpressRouteCrossConnection API service call.
    properties:
      nextLink:
        description: The URL to get the next set of results.
        readOnly: true
        type: string
      value:
        description: A list of ExpressRouteCrossConnection resources.
        items:
          $ref: '#/definitions/ExpressRouteCrossConnection'
        type: array
  ExpressRouteCrossConnectionPeering:
    allOf:
      - description: Reference to another subresource.
        properties:
          id:
            description: Resource ID.
            type: string
        x-ms-azure-resource: true
    description: Peering in an ExpressRoute Cross Connection resource.
    properties:
      etag:
        description: A unique read-only string that changes whenever the resource is updated.
        readOnly: true
        type: string
      name:
        description: Gets name of the resource that is unique within a resource group. This name can be used to access the resource.
        type: string
      properties:
        $ref: '#/definitions/ExpressRouteCrossConnectionPeeringProperties'
        x-ms-client-flatten: true
  ExpressRouteCrossConnectionPeeringList:
    description: Response for ListPeering API service call retrieves all peerings that belong to an ExpressRouteCrossConnection.
    properties:
      nextLink:
        description: The URL to get the next set of results.
        readOnly: true
        type: string
      value:
        description: The peerings in an express route cross connection.
        items:
          $ref: '#/definitions/ExpressRouteCrossConnectionPeering'
        type: array
  ExpressRouteCrossConnectionPeeringProperties:
    properties:
      azureASN:
        description: The Azure ASN.
        format: int32
        readOnly: true
        type: integer
      gatewayManagerEtag:
        description: The GatewayManager Etag.
        type: string
      ipv6PeeringConfig:
        description: Contains IPv6 peering config.
        properties:
          microsoftPeeringConfig:
            description: Specifies the peering configuration.
            properties:
              advertisedCommunities:
                description: The communities of bgp peering. Specified for microsoft peering
                items:
                  type: string
                type: array
              advertisedPublicPrefixes:
                description: The reference of AdvertisedPublicPrefixes.
                items:
                  type: string
                type: array
              advertisedPublicPrefixesState:
                description: 'AdvertisedPublicPrefixState of the Peering resource. Possible values are ''NotConfigured'', ''Configuring'', ''Configured'', and ''ValidationNeeded''.'
                enum:
                  - NotConfigured
                  - Configuring
                  - Configured
                  - ValidationNeeded
                type: string
                x-ms-enum:
                  modelAsString: true
                  name: ExpressRouteCircuitPeeringAdvertisedPublicPrefixState
              customerASN:
                description: The CustomerASN of the peering.
                format: int32
                type: integer
              legacyMode:
                description: The legacy mode of the peering.
                format: int32
                type: integer
              routingRegistryName:
                description: The RoutingRegistryName of the configuration.
                type: string
          primaryPeerAddressPrefix:
            description: The primary address prefix.
            type: string
          routeFilter:
            $ref: './routeFilter.json#/definitions/RouteFilter'
            description: The reference of the RouteFilter resource.
          secondaryPeerAddressPrefix:
            description: The secondary address prefix.
            type: string
          state:
            description: 'The state of peering. Possible values are: ''Disabled'' and ''Enabled'''
            enum:
              - Disabled
              - Enabled
            type: string
            x-ms-enum:
              modelAsString: true
              name: ExpressRouteCircuitPeeringState
      lastModifiedBy:
        description: Gets whether the provider or the customer last modified the peering.
        type: string
      microsoftPeeringConfig:
        description: Specifies the peering configuration.
        properties:
          advertisedCommunities:
            description: The communities of bgp peering. Specified for microsoft peering
            items:
              type: string
            type: array
          advertisedPublicPrefixes:
            description: The reference of AdvertisedPublicPrefixes.
            items:
              type: string
            type: array
          advertisedPublicPrefixesState:
            description: 'AdvertisedPublicPrefixState of the Peering resource. Possible values are ''NotConfigured'', ''Configuring'', ''Configured'', and ''ValidationNeeded''.'
            enum:
              - NotConfigured
              - Configuring
              - Configured
              - ValidationNeeded
            type: string
            x-ms-enum:
              modelAsString: true
              name: ExpressRouteCircuitPeeringAdvertisedPublicPrefixState
          customerASN:
            description: The CustomerASN of the peering.
            format: int32
            type: integer
          legacyMode:
            description: The legacy mode of the peering.
            format: int32
            type: integer
          routingRegistryName:
            description: The RoutingRegistryName of the configuration.
            type: string
      peerASN:
        description: The peer ASN.
        format: int64
        maximum: 4294967295
        minimum: 1
        type: integer
      peeringType:
        description: 'The PeeringType. Possible values are: ''AzurePublicPeering'', ''AzurePrivatePeering'', and ''MicrosoftPeering''.'
        enum:
          - AzurePublicPeering
          - AzurePrivatePeering
          - MicrosoftPeering
        type: string
        x-ms-enum:
          modelAsString: true
          name: ExpressRoutePeeringType
      primaryAzurePort:
        description: The primary port.
        readOnly: true
        type: string
      primaryPeerAddressPrefix:
        description: The primary address prefix.
        type: string
      provisioningState:
        description: 'Gets the provisioning state of the public IP resource. Possible values are: ''Updating'', ''Deleting'', and ''Failed''.'
        readOnly: true
        type: string
      secondaryAzurePort:
        description: The secondary port.
        readOnly: true
        type: string
      secondaryPeerAddressPrefix:
        description: The secondary address prefix.
        type: string
      sharedKey:
        description: The shared key.
        type: string
      state:
        description: 'The state of peering. Possible values are: ''Disabled'' and ''Enabled'''
        enum:
          - Disabled
          - Enabled
        type: string
        x-ms-enum:
          modelAsString: true
          name: ExpressRoutePeeringState
      vlanId:
        description: The VLAN ID.
        format: int32
        type: integer
  ExpressRouteCrossConnectionProperties:
    description: Properties of ExpressRouteCrossConnection.
    properties:
      bandwidthInMbps:
        description: The circuit bandwidth In Mbps.
        format: int32
        type: integer
      expressRouteCircuit:
        $ref: '#/definitions/ExpressRouteCircuitReference'
        description: The ExpressRouteCircuit
      peeringLocation:
        description: The peering location of the ExpressRoute circuit.
        type: string
      peerings:
        description: The list of peerings.
        items:
          $ref: '#/definitions/ExpressRouteCrossConnectionPeering'
        type: array
      primaryAzurePort:
        description: The name of the primary  port.
        readOnly: true
        type: string
      provisioningState:
        description: 'Gets the provisioning state of the public IP resource. Possible values are: ''Updating'', ''Deleting'', and ''Failed''.'
        readOnly: true
        type: string
      sTag:
        description: The identifier of the circuit traffic.
        readOnly: true
        type: integer
      secondaryAzurePort:
        description: The name of the secondary  port.
        readOnly: true
        type: string
      serviceProviderNotes:
        description: Additional read only notes set by the connectivity provider.
        type: string
      serviceProviderProvisioningState:
        description: 'The provisioning state of the circuit in the connectivity provider system. Possible values are ''NotProvisioned'', ''Provisioning'', ''Provisioned''.'
        enum:
          - NotProvisioned
          - Provisioning
          - Provisioned
          - Deprovisioning
        type: string
        x-ms-enum:
          modelAsString: true
          name: ServiceProviderProvisioningState
  ExpressRouteCrossConnectionRoutesTableSummary:
    description: The routes table associated with the ExpressRouteCircuit.
    properties:
      asn:
        description: Autonomous system number.
        format: int32
        type: integer
      neighbor:
        description: IP address of Neighbor router
        type: string
      stateOrPrefixesReceived:
        description: 'Current state of the BGP session, and the number of prefixes that have been received from a neighbor or peer group.'
        type: string
      upDown:
        description: 'The length of time that the BGP session has been in the Established state, or the current status if not in the Established state.'
        type: string
  ExpressRouteCrossConnectionsRoutesTableSummaryListResult:
    description: Response for ListRoutesTable associated with the Express Route Cross Connections.
    properties:
      nextLink:
        description: The URL to get the next set of results.
        readOnly: true
        type: string
      value:
        description: A list of the routes table.
        items:
          $ref: '#/definitions/ExpressRouteCrossConnectionRoutesTableSummary'
        type: array
